format_version: 10
pipelines:
  pilot-ascode:
    group: defaultGroup
    materials:
      app_git:
        git: https://github.com/vishal20034/branch-rule-test.git
        branch: main
    stages:
      - test:
          clean_workspace: true
          jobs:
            pytest:
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - C:/Users/X240/AppData/Local/Programs/Python/Python313/python.exe -m pip install pytest flask gunicorn && C:/Users/X240/AppData/Local/Programs/Python/Python313/python.exe -m pytest -q
      - deploy:
          jobs:
            azure:
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - tar -a -c -f package.zip app.py requirements.txt
                - exec:
                    command: powershell
                    arguments:
                      - -NoProfile
                      - -ExecutionPolicy
                      - Bypass
                      - -File
                      - deploy.ps1
