format_version: 10
pipelines:
  pilot-ascode:
    group: defaultGroup
    materials:
      app_git:
        git: https://github.com/vishal20034/branch-rule-test.git
        branch: main
    stages:
      - test:
          clean_workspace: true
          jobs:
            pytest:
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - C:/Users/X240/AppData/Local/Programs/Python/Python313/python.exe -m pip install -r requirements.txt pytest && C:/Users/X240/AppData/Local/Programs/Python/Python313/python.exe -m pytest -q
      - sonar:
          jobs:
            quality:
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - /c
                      - set SONAR_SCANNER_OPTS=-Xms64m -Xmx256m -XX:+UseSerialGC&& D:/sonar-scanner/bin/sonar-scanner.bat -Dsonar.host.url=%SONAR_HOST_URL% -Dsonar.token=%SONAR_TOKEN% -Dsonar.qualitygate.wait=true
      - deploy:
          jobs:
            azure:
              tasks:
                - exec:
                    command: powershell
                    arguments:
                      - -NoProfile
                      - -ExecutionPolicy
                      - Bypass
                      - -File
                      - deploy.ps1
