sonar.host.url=http://127.0.0.1:9000
sonar.projectKey=branch-rule-test
sonar.projectName=branch-rule-test
sonar.sources=.
sonar.tests=tests
sonar.python.version=3.11
sonar.exclusions=**/.git/**,**/venv/**,**/.venv/**,**/antenv/**,**/__pycache__/**,**/.github/**,**/package.zip,**/*.gocd.yaml,**/*.ps1,coverage.xml,**/sonar_mail.py,**/send_mail.py,**/azure-pipelines.yml
sonar.test.inclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=templates/**,static/**,**/sonar_mail.py,**/send_mail.py,**/sonar-scan.ps1
