sonar.host.url=http://127.0.0.1:9000
sonar.projectKey=squ_385f586c2187b5ee460084b472263d387ac941de
sonar.projectName=branch-rule-test
sonar.sources=.
sonar.python.version=3.11
sonar.exclusions=**/.git/**,**/venv/**,**/.venv/**,**/__pycache__/**
